class LocalLanguage {
  static final Map<String, Map<String, String>> _translations = {
    'Sesotho': {
      'Add Your Experiences': 'Kenya Mesebetsi Ya Hau',
      'Tell us what you do in your community:': 'Re bolelle hore na o etsa eng sechabeng sa hau:',
      'We will turn your Kasi experience into professional skills': 'Re tla fetolela maitemogelo a hau a Kasi a be mabokoo a porofešhenale',
      'Describe what you do...': 'Hlalosa hore na o etsa eng...',
      'Common Kasi Experiences:': 'Maitemogelo a Tloaelehileng a Kasi:',
      'No experiences added yet': 'Ha ho maitemogelo a kentseng hajane',
      'Create Professional CV': 'Theha CV ya Porofešhenale',
      'Please add at least one experience': 'Ka kopo, kenya maitemogelo a bobebe',
      'Professional CV Created': 'CV ya Porofešhenale e Thehilwe',
      'Skills & Abilities': 'Mabokoo le Bokgoni',
      'Work Experience': 'Maitemogelo a Mosebetsi',
      'Copy to Clipboard': 'Kopitsa ho Clipboard',
      'Your Professional CV is Ready': 'CV ya Hau ya Porofešhenale e Lokile',
      'Personal Information': 'Lintlha tsa Botho',
      'Full Name': 'Leina ka Botlalo',
      'Email': 'Email',
      'Phone': 'Nomoro ea Fono',
      'Location': 'Sebaka',
      'Save & Continue': 'Boloka o tsoele pele',
      'Generating your professional CV...': 'E theha CV ya hau ya porofešhenale...',
      'Download CV': 'Downloada CV',
      'Share CV': 'Arolelana CV',
      'Add more experiences': 'Kenya maitemogelo a mang',
      'What do you do in your community?': 'O etsa eng sechabeng sa hau?',
    },
    'isiZulu': {
      'Add Your Experiences': 'Faka Amava Akho',
      'Tell us what you do in your community:': 'Sitshele ukuthi wenzani emphakathini wakho:',
      'We will turn your Kasi experience into professional skills': 'Sizoguqula amava akho eKasi abe ngamakhono ochwepheshe',
      'Describe what you do...': 'Chaza ukuthi wenzani...',
      'Common Kasi Experiences:': 'Amava Avamile aseKasi:',
      'No experiences added yet': 'Awekho amava afakiwe okwamanje',
      'Create Professional CV': 'Yakha i-CV yobuchwepheshe',
      'Please add at least one experience': 'Sicela ufake okungenani amava ayodwa',
      'Professional CV Created': 'I-CV yobuchwepheshe yenziwe',
      'Skills & Abilities': 'Amakhono namandla',
      'Work Experience': 'Amava omsebenzi',
      'Copy to Clipboard': 'Kopisha kwi-Clipboard',
      'Your Professional CV is Ready': 'I-CV yakho yobuchwepheshe ilungile',
      'Personal Information': 'Imininingwane yomuntu siqu',
      'Full Name': 'Igama eliphelele',
      'Email': 'I-imeyili',
      'Phone': 'Inombolo yocingo',
      'Location': 'Indawo',
      'Save & Continue': 'Londoloza uqhubeke',
      'Generating your professional CV...': 'Kudala i-CV yakho yobuchwepheshe...',
      'Download CV': 'Landa i-CV',
      'Share CV': 'Yabelana nge-CV',
      'Add more experiences': 'Faka amava amaningi',
      'What do you do in your community?': 'Wenzani emphakathini wakho?',
    },
    'isiXhosa': {
      'Add Your Experiences': 'Yongeza Amava Akho',
      'Tell us what you do in your community:': 'Sixelele ukuba wenza ntoni kuluntu lwakho:',
      'We will turn your Kasi experience into professional skills': 'Siza kuguqula amava akho eKasi abe ngamakhono obugcisa',
      'Describe what you do...': 'Chaza ukuba wenza ntoni...',
      'Common Kasi Experiences:': 'Amava Aqhelekileyo aseKasi:',
      'No experiences added yet': 'Akukho mava ongeziweyo okwangoku',
      'Create Professional CV': 'Yenza i-CV yobugcisa',
      'Please add at least one experience': 'Nceda yongeza ubuncinci amava omnye',
      'Professional CV Created': 'I-CV yobugcisa yenziwe',
      'Skills & Abilities': 'Amakhono namandla',
      'Work Experience': 'Amava omsebenzi',
      'Copy to Clipboard': 'Kopa kwi-Clipboard',
      'Your Professional CV is Ready': 'I-CV yakho yobugcisa ilungile',
      'Personal Information': 'Iinkcukacha zomntu',
      'Full Name': 'Igama elipheleleyo',
      'Email': 'I-imeyili',
      'Phone': 'Inombolo yomnxeba',
      'Location': 'Indawo',
      'Save & Continue': 'Gcina uqhubeke',
      'Generating your professional CV...': 'Iyenza i-CV yakho yobugcisa...',
      'Download CV': 'Khuphela i-CV',
      'Share CV': 'Yabelana nge-CV',
      'Add more experiences': 'Yongeza amava amaninzi',
      'What do you do in your community?': 'Wenza ntoni eluntwini lakho?',
    },
    'Afrikaans': {
      'Add Your Experiences': 'Voeg Jou Ervaring By',
      'Tell us what you do in your community:': 'Vertel ons wat jy in jou gemeenskap doen:',
      'We will turn your Kasi experience into professional skills': 'Ons sal jou Kasi-ervaring in professionele vaardighede omskep',
      'Describe what you do...': 'Beskryf wat jy doen...',
      'Common Kasi Experiences:': 'Algemene Kasi Ervarings:',
      'No experiences added yet': 'Nog geen ervarings bygevoeg nie',
      'Create Professional CV': 'Skep Professionele CV',
      'Please add at least one experience': 'Voeg asseblief ten minste een ervaring by',
      'Professional CV Created': 'Professionele CV Geskep',
      'Skills & Abilities': 'Vaardighede & Vermoëns',
      'Work Experience': 'Werkervaring',
      'Copy to Clipboard': 'Kopieer na Knipbord',
      'Your Professional CV is Ready': 'Jou Professionele CV is Reg',
      'Personal Information': 'Persoonlike Inligting',
      'Full Name': 'Volle Naam',
      'Email': 'E-pos',
      'Phone': 'Telefoon',
      'Location': 'Ligging',
      'Save & Continue': 'Stoor & Gaan Aan',
      'Generating your professional CV...': 'Skep jou professionele CV...',
      'Download CV': 'Laai CV Af',
      'Share CV': 'Deel CV',
      'Add more experiences': 'Voeg meer ervarings by',
      'What do you do in your community?': 'Wat doen jy in jou gemeenskap?',
    },
    'Setswana': {
      'Add Your Experiences': 'Tsenya Maitemogelo a Gago',
      'Tell us what you do in your community:': 'Re bolelele gore o dira eng mo setšhabeng sa gago:',
      'We will turn your Kasi experience into professional skills': 'Re tla fetolela maitemogelo a gago a Kasi a nne bokgoni jwa porofešhenale',
      'Describe what you do...': 'Hlalosa gore o dira eng...',
      'Common Kasi Experiences:': 'Maitemogelo a a Tlwaelegileng a Kasi:',
      'No experiences added yet': 'Ga go na maitemogelo a a tsentsweng isago',
      'Create Professional CV': 'Dirisa CV ya Porofešhenale',
      'Please add at least one experience': 'Ka kopo, tsenya maitemogelo a le nosi',
      'Professional CV Created': 'CV ya Porofešhenale e Dirilwe',
      'Skills & Abilities': 'Bokgoni le Dikgono',
      'Work Experience': 'Maitemogelo a Tiro',
      'Copy to Clipboard': 'Kopitsa mo Clipboard',
      'Your Professional CV is Ready': 'CV ya Gago ya Porofešhenale e a siama',
      'Personal Information': 'Tshedimosetso ya Botho',
      'Full Name': 'Maina a Bophara',
      'Email': 'Email',
      'Phone': 'Nomoro ya Founo',
      'Location': 'Lefelo',
      'Save & Continue': 'Boloka o tswelele',
      'Generating your professional CV...': 'E dira CV ya gago ya porofešhenale...',
      'Download CV': 'Downloada CV',
      'Share CV': 'Abelana ka CV',
      'Add more experiences': 'Tsenya maitemogelo a mangwe',
      'What do you do in your community?': 'O dira eng mo setšhabeng sa gago?',
    },
  };

  static String getTranslation(String text, String language) {
    if (language == 'English') return text;
    
    final languageTranslations = _translations[language];
    if (languageTranslations != null && languageTranslations.containsKey(text)) {
      return languageTranslations[text]!;
    }
    
    return text; // Fallback to English
  }
}